-- Eight weeks of store trading for every listed outlet product, plus the
-- agent knowledge built from it. Runs once: it skips when the
-- 'seed-baseline' simulation run already exists. Every row is marked
-- simulated = true under that run. Plain DELETEs on the append-only ledger and
-- observations are refused; to regenerate, remove the run with
--   SELECT inventory.delete_simulation_run(id) FROM inventory.simulation_runs WHERE code = 'seed-baseline';
--
-- Deterministic: every "random" value is a hash of outlet, product and date.
-- Model per outlet product, per day:
--   * deliveries on a schedule (perishables Mon/Wed/Fri, other chilled Mon/Thu,
--     Fresh ambient Mon, Style and Tech Tue), sized to cover until the next
--     delivery with a per-store ordering bias, rounded up to whole packs;
--   * demand = average daily sales x weekday pattern x slow trend x noise,
--     sold first-expiry-first-out; unmet demand is recorded as lost sales;
--   * lots past their expiry are written off as EXPIRED, rare DAMAGED items,
--     and Sunday counts that post small ADJUSTED variances.
-- Demo scenario: OUT034 receives 4 crates of Fresh milk 1 L last Monday and
-- only sells about 28 bottles, so about 20 expire (the order assistant's
-- "Are you sure?" example).

CREATE OR REPLACE FUNCTION pg_temp.h(t text) RETURNS double precision
LANGUAGE sql IMMUTABLE AS $$ SELECT ('x' || substr(md5(t), 1, 7))::bit(28)::int / 268435455.0 $$;

INSERT INTO ai.agents (code, name, description, audience) VALUES
  ('A1', 'Order assistant', 'Turns a pasted or spoken order into order lines for the store manager to confirm, and warns about recent waste or stock-outs.', 'Store manager'),
  ('A2', 'Dashboard assistant', 'Builds and changes a dashboard from a plain request, using only the person''s own data.', 'Store manager, dispatcher later'),
  ('A3', 'Habit helper', 'Notices repeated actions and offers to do them, learning from each yes or no.', 'All roles'),
  ('A4', 'Workflow builder', 'Turns a plain description into an automated workflow, tests it and saves it on yes.', 'Anyone'),
  ('A5', 'Customer simulation', 'Simulates shoppers buying from each store so sales, waste and stock can be modelled.', 'Development and demos')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, audience = EXCLUDED.audience;

DO $$
DECLARE
  this_monday date := date_trunc('week', current_date)::date;
  v_start date := date_trunc('week', current_date)::date - 56;
  v_end date := current_date - 1;
  demo_monday date := date_trunc('week', current_date)::date - 7;
  run uuid;
  r record;
  d integer;
  n_days integer;
  day date;
  dow integer;
  key text;
  last_outlet text := '';
  sale_ids uuid[];
  i integer;
  first_open integer;
  on_hand integer;
  rate double precision;
  trend double precision;
  bias double precision;
  is_demo boolean;
  delivery boolean;
  cover integer;
  next_gap integer;
  target integer;
  packs integer;
  qty integer;
  demand integer;
  left_to_sell integer;
  take integer;
  sold integer;
  line uuid;
  variance integer;
  -- Per outlet product, built in memory and written with one insert per table.
  bt_id uuid[]; bt_qty integer[]; bt_recv integer[]; bt_exp date[]; bt_at timestamptz[]; bt_src text[]; bt_ref text[];
  sl_id uuid[]; sl_sale uuid[]; sl_qty integer[];
  mv_batch uuid[]; mv_type text[]; mv_qty integer[]; mv_reason text[]; mv_src text[]; mv_ref text[]; mv_line uuid[]; mv_at timestamptz[];
  sc_counted integer[]; sc_system integer[]; sc_at timestamptz[];
  ls_day date[]; ls_qty integer[];
BEGIN
  IF EXISTS (SELECT 1 FROM inventory.simulation_runs WHERE code = 'seed-baseline') THEN
    RAISE NOTICE 'inventory history already seeded; skipping';
    RETURN;
  END IF;

  INSERT INTO inventory.simulation_runs (code, scenario, seed, period_start, period_end, created_by)
  VALUES ('seed-baseline', 'Eight weeks of store trading generated by the customer simulation (A5) for development and demos', 2026, v_start, v_end, 'seed')
  RETURNING id INTO run;

  -- One end-of-day till summary per outlet per day; lines are attached below.
  INSERT INTO inventory.sales (outlet_id, business_date, sold_at, channel, receipt_no, simulated, simulation_run_id)
  SELECT o.id, g::date, (g::date + time '21:00') AT TIME ZONE 'Asia/Colombo', 'simulated', 'Z-' || to_char(g, 'YYYYMMDD'), true, run
  FROM shared.outlets o CROSS JOIN generate_series(v_start, v_end, interval '1 day') g;

  CREATE TEMP TABLE lost_sales (outlet_id text, product_id text, sale_day date, lost integer) ON COMMIT DROP;

  n_days := v_end - v_start;

  FOR r IN
    SELECT op.outlet_id, op.product_id, op.avg_daily_sales_each AS avg_rate, p.units_per_pack, p.temperature, p.brand,
           COALESCE(f.perishable, false) AS perishable, COALESCE(f.shelf_life_days, 3650) AS shelf, pr.unit_price
    FROM shared.outlet_products op
    JOIN shared.products p ON p.id = op.product_id
    LEFT JOIN shared.product_fresh f ON f.product_id = p.id
    JOIN shared.product_prices pr ON pr.product_id = p.id AND pr.price_list = 'retail' AND pr.effective_to IS NULL
    WHERE op.listed AND op.avg_daily_sales_each > 0 AND p.status = 'active'
    ORDER BY op.outlet_id, op.product_id
  LOOP
    IF r.outlet_id <> last_outlet THEN
      SELECT array_agg(s.id ORDER BY s.business_date) INTO sale_ids
      FROM inventory.sales s WHERE s.outlet_id = r.outlet_id AND s.simulation_run_id = run;
      last_outlet := r.outlet_id;
    END IF;

    key := r.outlet_id || '|' || r.product_id;
    trend := (pg_temp.h(key || '|trend') - 0.5) * 0.7;      -- -35% to +35% over the period
    bias := 0.95 + pg_temp.h(key || '|bias') * 0.35;          -- some stores order generously
    bt_id := '{}'; bt_qty := '{}'; bt_recv := '{}'; bt_exp := '{}'; bt_at := '{}'; bt_src := '{}'; bt_ref := '{}';
    sl_id := '{}'; sl_sale := '{}'; sl_qty := '{}';
    mv_batch := '{}'; mv_type := '{}'; mv_qty := '{}'; mv_reason := '{}'; mv_src := '{}'; mv_ref := '{}'; mv_line := '{}'; mv_at := '{}';
    sc_counted := '{}'; sc_system := '{}'; sc_at := '{}';
    ls_day := '{}'; ls_qty := '{}';
    on_hand := 0;
    first_open := 1;

    FOR d IN 0..n_days LOOP
      day := v_start + d;
      dow := extract(isodow FROM day);
      is_demo := r.outlet_id = 'OUT034' AND r.product_id = 'FR-MILK-1L' AND day BETWEEN demo_monday AND demo_monday + 6;

      -- Delivery schedule and days of cover until the next delivery.
      IF r.perishable AND r.shelf <= 14 THEN
        delivery := dow IN (1, 3, 5);
        next_gap := CASE dow WHEN 1 THEN 2 WHEN 3 THEN 2 ELSE 3 END;
      ELSIF r.temperature = 'chilled' THEN
        delivery := dow IN (1, 4);
        next_gap := CASE dow WHEN 1 THEN 3 ELSE 4 END;
      ELSIF r.brand = 'Fresh' THEN
        delivery := dow = 1; next_gap := 7;
      ELSE
        delivery := dow = 2; next_gap := 7;
      END IF;
      IF d = 0 THEN delivery := true; next_gap := 7; END IF;
      IF is_demo THEN delivery := dow = 1; END IF;

      IF delivery THEN
        IF is_demo THEN
          packs := 4;
        ELSE
          cover := next_gap + CASE WHEN r.perishable THEN 0 ELSE 3 END;
          target := ceil(r.avg_rate * cover * bias)::int;
          packs := CASE WHEN target > on_hand THEN ceil((target - on_hand)::numeric / r.units_per_pack)::int ELSE 0 END;
        END IF;
        IF packs > 0 THEN
          qty := packs * r.units_per_pack;
          bt_id := bt_id || gen_random_uuid();
          bt_qty := bt_qty || qty;
          bt_recv := bt_recv || qty;
          bt_exp := bt_exp || CASE WHEN r.shelf < 3650 THEN day + r.shelf - 1 ELSE date '9999-12-31' END;
          bt_at := bt_at || ((day + time '06:30') AT TIME ZONE 'Asia/Colombo');
          bt_src := bt_src || CASE WHEN d = 0 THEN 'opening_balance' ELSE 'receipt' END;
          bt_ref := bt_ref || ('GRN-' || r.outlet_id || '-' || to_char(day, 'YYYYMMDD'));
          mv_batch := mv_batch || bt_id[array_length(bt_id, 1)];
          mv_type := mv_type || 'RECEIVED'::text;
          mv_qty := mv_qty || qty;
          mv_reason := mv_reason || CASE WHEN d = 0 THEN 'Opening balance' ELSE packs || ' x ' || r.units_per_pack END;
          mv_src := mv_src || CASE WHEN d = 0 THEN 'opening_balance' ELSE 'receipt' END;
          mv_ref := mv_ref || ('GRN-' || r.outlet_id || '-' || to_char(day, 'YYYYMMDD'));
          mv_line := mv_line || NULL::uuid;
          mv_at := mv_at || ((day + time '06:30') AT TIME ZONE 'Asia/Colombo');
          on_hand := on_hand + qty;
        END IF;
      END IF;

      -- Demand: weekday pattern, slow trend and noise.
      rate := r.avg_rate
              * CASE dow WHEN 5 THEN 1.10 WHEN 6 THEN 1.25 WHEN 7 THEN 1.15 WHEN 1 THEN 0.90 ELSE 0.95 END
              * (1 + trend * (d::double precision / n_days - 0.5))
              * (0.55 + 0.9 * pg_temp.h(key || '|' || day));
      demand := CASE WHEN is_demo THEN 4 ELSE floor(rate + pg_temp.h(key || '|frac|' || day))::int END;

      -- Sell first-expiry-first-out. Lots of one product share a shelf life, so
      -- arrival order is expiry order.
      sold := 0; left_to_sell := demand; line := NULL;
      IF demand > 0 AND on_hand > 0 THEN
        line := gen_random_uuid();
        i := first_open;
        WHILE left_to_sell > 0 AND i <= coalesce(array_length(bt_qty, 1), 0) LOOP
          IF bt_qty[i] > 0 THEN
            take := least(bt_qty[i], left_to_sell);
            mv_batch := mv_batch || bt_id[i]; mv_type := mv_type || 'SOLD'::text; mv_qty := mv_qty || (-take);
            mv_reason := mv_reason || ''::text; mv_src := mv_src || 'sale'::text; mv_ref := mv_ref || ('Z-' || to_char(day, 'YYYYMMDD'));
            mv_line := mv_line || line; mv_at := mv_at || ((day + time '21:00') AT TIME ZONE 'Asia/Colombo');
            bt_qty[i] := bt_qty[i] - take; left_to_sell := left_to_sell - take; sold := sold + take;
          END IF;
          i := i + 1;
        END LOOP;
        on_hand := on_hand - sold;
        sl_id := sl_id || line; sl_sale := sl_sale || sale_ids[d + 1]; sl_qty := sl_qty || sold;
      END IF;
      IF left_to_sell > 0 THEN
        ls_day := ls_day || day; ls_qty := ls_qty || left_to_sell;
      END IF;

      -- Occasional breakage on the shelf.
      IF on_hand > 0 AND pg_temp.h(key || '|damage|' || day) < 0.012 THEN
        i := first_open;
        WHILE bt_qty[i] = 0 LOOP i := i + 1; END LOOP;
        mv_batch := mv_batch || bt_id[i]; mv_type := mv_type || 'DAMAGED'::text; mv_qty := mv_qty || (-1);
        mv_reason := mv_reason || 'Damaged on shelf'::text; mv_src := mv_src || 'write_off'::text; mv_ref := mv_ref || ''::text;
        mv_line := mv_line || NULL::uuid; mv_at := mv_at || ((day + time '15:00') AT TIME ZONE 'Asia/Colombo');
        bt_qty[i] := bt_qty[i] - 1; on_hand := on_hand - 1;
      END IF;

      -- End of day: lots on their last day are written off.
      i := first_open;
      WHILE i <= coalesce(array_length(bt_qty, 1), 0) AND bt_exp[i] <= day LOOP
        IF bt_qty[i] > 0 THEN
          mv_batch := mv_batch || bt_id[i]; mv_type := mv_type || 'EXPIRED'::text; mv_qty := mv_qty || (-bt_qty[i]);
          mv_reason := mv_reason || 'Past expiry'::text; mv_src := mv_src || 'write_off'::text; mv_ref := mv_ref || ''::text;
          mv_line := mv_line || NULL::uuid; mv_at := mv_at || ((day + time '22:00') AT TIME ZONE 'Asia/Colombo');
          on_hand := on_hand - bt_qty[i]; bt_qty[i] := 0;
        END IF;
        i := i + 1;
      END LOOP;
      WHILE first_open <= coalesce(array_length(bt_qty, 1), 0) AND bt_qty[first_open] = 0 LOOP
        first_open := first_open + 1;
      END LOOP;

      -- Sunday stock count for some lines; small shrinkage is posted as an adjustment.
      IF dow = 7 AND pg_temp.h(key || '|count|' || day) < 0.3 THEN
        variance := CASE WHEN on_hand > 0 AND pg_temp.h(key || '|shrink|' || day) < 0.35
                         THEN -least(on_hand, 1 + floor(pg_temp.h(key || '|shrinkqty|' || day) * 2)::int) ELSE 0 END;
        sc_counted := sc_counted || (on_hand + variance); sc_system := sc_system || on_hand;
        sc_at := sc_at || ((day + time '22:30') AT TIME ZONE 'Asia/Colombo');
        i := first_open;
        WHILE variance < 0 LOOP
          IF bt_qty[i] > 0 THEN
            take := least(bt_qty[i], -variance);
            mv_batch := mv_batch || bt_id[i]; mv_type := mv_type || 'ADJUSTED'::text; mv_qty := mv_qty || (-take);
            mv_reason := mv_reason || 'Stock count variance'::text; mv_src := mv_src || 'stock_count'::text; mv_ref := mv_ref || ''::text;
            mv_line := mv_line || NULL::uuid; mv_at := mv_at || ((day + time '22:30') AT TIME ZONE 'Asia/Colombo');
            bt_qty[i] := bt_qty[i] - take; on_hand := on_hand - take; variance := variance + take;
          END IF;
          i := i + 1;
        END LOOP;
      END IF;
    END LOOP;

    INSERT INTO inventory.stock_batches (id, outlet_id, product_id, source_type, source_ref, received_each, remaining_each, received_at, expires_on, simulated, simulation_run_id)
    SELECT u.id, r.outlet_id, r.product_id, u.src, u.ref, u.recv, u.qty, u.at, NULLIF(u.exp, date '9999-12-31'), true, run
    FROM unnest(bt_id, bt_src, bt_ref, bt_recv, bt_qty, bt_at, bt_exp) AS u(id, src, ref, recv, qty, at, exp);

    INSERT INTO inventory.sale_lines (id, sale_id, product_id, quantity_each, unit_price, line_amount)
    SELECT u.id, u.sale, r.product_id, u.qty, r.unit_price, u.qty * r.unit_price
    FROM unnest(sl_id, sl_sale, sl_qty) AS u(id, sale, qty);

    INSERT INTO inventory.stock_movements (outlet_id, product_id, batch_id, movement_type, quantity_each, reason, source_type, source_ref, sale_line_id, occurred_at, recorded_by, simulated, simulation_run_id)
    SELECT r.outlet_id, r.product_id, u.batch, u.typ, u.qty, u.reason, u.src, u.ref, u.line, u.at, 'seed:customer-simulation', true, run
    FROM unnest(mv_batch, mv_type, mv_qty, mv_reason, mv_src, mv_ref, mv_line, mv_at) WITH ORDINALITY AS u(batch, typ, qty, reason, src, ref, line, at, ord)
    ORDER BY u.ord;

    INSERT INTO inventory.stock_counts (outlet_id, product_id, counted_each, system_each, counted_at, counted_by, simulated, simulation_run_id)
    SELECT r.outlet_id, r.product_id, u.counted, u.sys, u.at, 'seed:customer-simulation', true, run
    FROM unnest(sc_counted, sc_system, sc_at) AS u(counted, sys, at);

    INSERT INTO lost_sales (outlet_id, product_id, sale_day, lost)
    SELECT r.outlet_id, r.product_id, u.d, u.qty FROM unnest(ls_day, ls_qty) AS u(d, qty);

    INSERT INTO inventory.stock_levels (outlet_id, product_id, on_hand_each, last_movement_at)
    VALUES (r.outlet_id, r.product_id, on_hand, (v_end + time '22:30') AT TIME ZONE 'Asia/Colombo')
    ON CONFLICT (outlet_id, product_id) DO UPDATE SET on_hand_each = EXCLUDED.on_hand_each, last_movement_at = EXCLUDED.last_movement_at, updated_at = now();
  END LOOP;

  -- Fresh tables have no planner statistics yet; without them the set-based
  -- steps below pick nested scans and take minutes.
  ANALYZE inventory.sales; ANALYZE inventory.sale_lines; ANALYZE inventory.stock_movements; ANALYZE lost_sales;

  DELETE FROM inventory.sales s WHERE s.simulation_run_id = run AND NOT EXISTS (SELECT 1 FROM inventory.sale_lines l WHERE l.sale_id = s.id);
  UPDATE inventory.sales s SET total_amount = t.amount
  FROM (SELECT sale_id, sum(line_amount) AS amount FROM inventory.sale_lines GROUP BY sale_id) t
  WHERE t.sale_id = s.id AND s.simulation_run_id = run;

  -- Raw weekly facts per outlet product, for the full weeks in the period.
  INSERT INTO ai.observations (subject_type, subject_id, metric, value, unit, period_start, period_end, source, raw, simulated, simulation_run_id)
  SELECT 'outlet_product', w.outlet_id || ':' || w.product_id, m.metric, m.value, 'each', w.week_start, w.week_start + 6, 'inventory_ledger',
         jsonb_build_object('outlet_id', w.outlet_id, 'product_id', w.product_id, 'received', w.received, 'sold', w.sold,
                            'expired', w.expired, 'damaged', w.damaged, 'adjusted', w.adjusted, 'lost_sales', w.lost), true, run
  FROM (
    SELECT g.*, COALESCE(lw.lost, 0) AS lost
    FROM (
      SELECT mv.outlet_id, mv.product_id, date_trunc('week', (mv.occurred_at AT TIME ZONE 'Asia/Colombo'))::date AS week_start,
             sum(mv.quantity_each) FILTER (WHERE mv.movement_type = 'RECEIVED' AND mv.source_type = 'receipt') AS received,
             -sum(mv.quantity_each) FILTER (WHERE mv.movement_type = 'SOLD') AS sold,
             -sum(mv.quantity_each) FILTER (WHERE mv.movement_type = 'EXPIRED') AS expired,
             -sum(mv.quantity_each) FILTER (WHERE mv.movement_type = 'DAMAGED') AS damaged,
             -sum(mv.quantity_each) FILTER (WHERE mv.movement_type = 'ADJUSTED') AS adjusted
      FROM inventory.stock_movements mv
      WHERE mv.simulation_run_id = run AND (mv.occurred_at AT TIME ZONE 'Asia/Colombo')::date < this_monday
      GROUP BY 1, 2, 3
    ) g
    LEFT JOIN (
      SELECT ls.outlet_id, ls.product_id, date_trunc('week', ls.sale_day)::date AS week_start, sum(ls.lost) AS lost
      FROM lost_sales ls GROUP BY 1, 2, 3
    ) lw ON lw.outlet_id = g.outlet_id AND lw.product_id = g.product_id AND lw.week_start = g.week_start
  ) w
  CROSS JOIN LATERAL (VALUES
    ('units_received', COALESCE(w.received, 0)),
    ('units_sold', COALESCE(w.sold, 0)),
    ('units_wasted', COALESCE(w.expired, 0) + COALESCE(w.damaged, 0)),
    ('lost_sales', w.lost)
  ) AS m(metric, value)
  WHERE w.week_start >= v_start;

  -- Weekly takings and waste value per outlet.
  INSERT INTO ai.observations (subject_type, subject_id, metric, value, unit, period_start, period_end, source, raw, simulated, simulation_run_id)
  SELECT 'outlet', x.outlet_id, x.metric, x.value, 'LKR', x.week_start, x.week_start + 6, 'inventory_ledger', jsonb_build_object('outlet_id', x.outlet_id), true, run
  FROM (
    SELECT mv.outlet_id, date_trunc('week', (mv.occurred_at AT TIME ZONE 'Asia/Colombo'))::date AS week_start,
           'sales_value' AS metric, sum(-mv.quantity_each * pr.unit_price) AS value
    FROM inventory.stock_movements mv
    JOIN shared.product_prices pr ON pr.product_id = mv.product_id AND pr.price_list = 'retail' AND pr.effective_to IS NULL
    WHERE mv.simulation_run_id = run AND mv.movement_type = 'SOLD' AND (mv.occurred_at AT TIME ZONE 'Asia/Colombo')::date < this_monday
    GROUP BY 1, 2
    UNION ALL
    SELECT mv.outlet_id, date_trunc('week', (mv.occurred_at AT TIME ZONE 'Asia/Colombo'))::date,
           'waste_value', sum(-mv.quantity_each * pr.unit_price)
    FROM inventory.stock_movements mv
    JOIN shared.product_prices pr ON pr.product_id = mv.product_id AND pr.price_list = 'retail' AND pr.effective_to IS NULL
    WHERE mv.simulation_run_id = run AND mv.movement_type IN ('EXPIRED', 'DAMAGED', 'WASTED') AND (mv.occurred_at AT TIME ZONE 'Asia/Colombo')::date < this_monday
    GROUP BY 1, 2
  ) x
  WHERE x.week_start >= v_start;

  ANALYZE ai.observations;

  -- Insights the agents act on, valid for the current week.
  WITH last_week AS (
    SELECT o.subject_id, (o.raw ->> 'outlet_id') AS outlet_id, (o.raw ->> 'product_id') AS product_id,
           max(o.value) FILTER (WHERE o.metric = 'units_received') AS received,
           max(o.value) FILTER (WHERE o.metric = 'units_sold') AS sold,
           max(o.value) FILTER (WHERE o.metric = 'units_wasted') AS wasted,
           array_agg(o.id ORDER BY o.id) AS ids
    FROM ai.observations o
    WHERE o.subject_type = 'outlet_product' AND o.period_start = this_monday - 7 AND o.source = 'inventory_ledger'
    GROUP BY 1, 2, 3
  )
  INSERT INTO ai.insights (agent_code, kind, subject_type, subject_id, outlet_id, product_id, summary, score, evidence, observation_ids, valid_from, valid_until)
  SELECT 'A1', 'WASTE_RISK', 'outlet_product', lw.subject_id, lw.outlet_id, lw.product_id,
         format('%s of %s %s received last week were thrown away at %s.', lw.wasted::int, lw.received::int, p.each_name || 's of ' || p.name, lw.outlet_id),
         least(1, round((lw.wasted / greatest(lw.received, 1))::numeric, 4)),
         jsonb_build_object('week_start', this_monday - 7, 'received', lw.received, 'sold', lw.sold, 'wasted', lw.wasted,
                            'waste_rate', round((lw.wasted / greatest(lw.received, 1))::numeric, 3)),
         lw.ids, this_monday, this_monday + 6
  FROM last_week lw JOIN shared.products p ON p.id = lw.product_id
  WHERE lw.received > 0 AND lw.wasted >= 6 AND lw.wasted / lw.received >= 0.15;

  WITH recent AS (
    SELECT o.subject_id, (o.raw ->> 'outlet_id') AS outlet_id, (o.raw ->> 'product_id') AS product_id,
           count(*) FILTER (WHERE o.metric = 'lost_sales' AND o.value > 0) AS weeks_short,
           sum(o.value) FILTER (WHERE o.metric = 'lost_sales') AS lost,
           sum(o.value) FILTER (WHERE o.metric = 'units_sold') AS sold,
           array_agg(o.id ORDER BY o.id) AS ids
    FROM ai.observations o
    WHERE o.subject_type = 'outlet_product' AND o.metric IN ('lost_sales', 'units_sold') AND o.period_start >= this_monday - 21 AND o.source = 'inventory_ledger'
    GROUP BY 1, 2, 3
  )
  INSERT INTO ai.insights (agent_code, kind, subject_type, subject_id, outlet_id, product_id, summary, score, evidence, observation_ids, valid_from, valid_until)
  SELECT 'A1', 'STOCKOUT_RISK', 'outlet_product', rc.subject_id, rc.outlet_id, rc.product_id,
         format('%s ran out in %s of the last 3 weeks at %s; about %s sales were missed.', p.name, rc.weeks_short, rc.outlet_id, rc.lost::int),
         least(1, round((rc.weeks_short / 3.0)::numeric, 4)),
         jsonb_build_object('weeks_with_stockouts', rc.weeks_short, 'missed_sales', rc.lost, 'from', this_monday - 21),
         rc.ids, this_monday, this_monday + 6
  FROM recent rc JOIN shared.products p ON p.id = rc.product_id
  -- Only when missed sales are material: at least 10 items and 8% of what sold.
  WHERE rc.weeks_short >= 2 AND rc.lost >= greatest(10, 0.08 * rc.sold);

  WITH sold AS (
    SELECT o.subject_id, (o.raw ->> 'outlet_id') AS outlet_id, (o.raw ->> 'product_id') AS product_id,
           avg(o.value) FILTER (WHERE o.period_start >= this_monday - 14) AS recent,
           avg(o.value) FILTER (WHERE o.period_start < this_monday - 14 AND o.period_start >= this_monday - 42) AS before,
           array_agg(o.id ORDER BY o.id) AS ids
    FROM ai.observations o
    WHERE o.subject_type = 'outlet_product' AND o.metric = 'units_sold' AND o.period_start >= this_monday - 42 AND o.source = 'inventory_ledger'
    GROUP BY 1, 2, 3
  )
  INSERT INTO ai.insights (agent_code, kind, subject_type, subject_id, outlet_id, product_id, summary, score, evidence, observation_ids, valid_from, valid_until)
  SELECT 'A2', CASE WHEN s.recent > s.before THEN 'TREND_UP' ELSE 'TREND_DOWN' END, 'outlet_product', s.subject_id, s.outlet_id, s.product_id,
         format('%s sales at %s are %s%% %s than the four weeks before.', p.name, s.outlet_id, round(abs(s.recent / s.before - 1) * 100),
                CASE WHEN s.recent > s.before THEN 'higher' ELSE 'lower' END),
         least(1, round(abs(s.recent / s.before - 1)::numeric, 4)),
         jsonb_build_object('recent_weekly_avg', round(s.recent::numeric, 1), 'previous_weekly_avg', round(s.before::numeric, 1)),
         s.ids, this_monday, this_monday + 6
  FROM sold s JOIN shared.products p ON p.id = s.product_id
  WHERE s.before >= 7 AND abs(s.recent / s.before - 1) >= 0.25;

  RAISE NOTICE 'inventory history seeded for % to %', v_start, v_end;
END $$;
