// Sinhala and Tamil text for the feature-audit gap work. Keys are the English source strings.
export const auditGapLabels = {
  si: {
    "Estimated order volume for the next ten weeks, by depot and brand, to plan vehicles, drivers and refrigerated capacity.": "වාහන, රියදුරන් සහ ශීතකරණ ධාරිතාව සැලසුම් කිරීමට, ඩිපෝව සහ වෙළඳ නාමය අනුව ඉදිරි සති දහයේ ඇස්තමේන්තුගත ඇණවුම් පරිමාව.",
    "widens with distance": "දුර වැඩි වන විට පුළුල් වේ",
    "Operating calendar set up to": "මෙහෙයුම් දින දර්ශනය සකසා ඇත්තේ",
    "Later days use the usual weekday pattern.": "පසු දින සාමාන්‍ය සතියේ දින රටාව භාවිතා කරයි.",
    "Operating calendar is not set for these weeks. Days use the usual weekday pattern.": "මෙම සති සඳහා මෙහෙයුම් දින දර්ශනය සකසා නැත. දින සාමාන්‍ය සතියේ දින රටාව භාවිතා කරයි.",
    "may be delayed by": "ප්‍රමාද විය හැක්කේ මේ නිසා:",
    "may delay": "ප්‍රමාද කළ හැක",
    "issues on this trip": "මෙම ගමනේ ගැටලු",
    "Acknowledge all": "සියල්ල පිළිගන්න",
    "Ranked by impact and grouped by trip: breakdowns and chilled goods, closing windows, silent trips, road risks, then loading and delivery issues": "බලපෑම අනුව පෙළගස්වා ගමන අනුව කාණ්ඩ කර ඇත: බිඳවැටීම් සහ සිසිල් භාණ්ඩ, වැසෙන කාල සීමා, නිහඬ ගමන්, මාර්ග අවදානම්, ඉන්පසු පැටවීම් සහ බෙදාහැරීම් ගැටලු",
    "Hearing": "ඇසෙන්නේ",
    "Listening… say the items and quantities, then tap Stop.": "සවන් දෙමින්… අයිතම සහ ප්‍රමාණ කියා, ඉන්පසු නවත්වන්න ඔබන්න.",
    "Speak your order": "ඔබේ ඇණවුම කියන්න",
    "Paste, type or speak your order": "ඔබේ ඇණවුම අලවන්න, ටයිප් කරන්න හෝ කියන්න",
    "Microphone access is blocked. Allow the microphone for this site, or type the order.": "මයික්‍රෆෝනයට ප්‍රවේශය අවහිර කර ඇත. මෙම අඩවියට මයික්‍රෆෝනයට ඉඩ දෙන්න, නැතහොත් ඇණවුම ටයිප් කරන්න.",
    "No microphone was found. Type the order instead.": "මයික්‍රෆෝනයක් හමු නොවීය. ඒ වෙනුවට ඇණවුම ටයිප් කරන්න.",
    "Speech could not be turned into text without a connection. Type the order instead.": "සම්බන්ධතාවක් නොමැතිව කථනය පෙළට හැරවිය නොහැකි විය. ඒ වෙනුවට ඇණවුම ටයිප් කරන්න.",
    "This browser cannot listen in the chosen language. Switch to English or type the order.": "මෙම බ්‍රවුසරයට තෝරාගත් භාෂාවෙන් සවන් දිය නොහැක. ඉංග්‍රීසියට මාරු වන්න හෝ ඇණවුම ටයිප් කරන්න.",
    "Nothing was heard. Tap Speak and try again.": "කිසිවක් ඇසුණේ නැත. කියන්න ඔබා නැවත උත්සාහ කරන්න.",
    "Temperature on arrival (°C, optional)": "පැමිණීමේදී උෂ්ණත්වය (°C, අත්‍යවශ්‍ය නොවේ)",
    "e.g. 4.5": "උදා. 4.5",
    "Enter a reading between -40 and 60 °C.": "-40 සහ 60 °C අතර කියවීමක් ඇතුළත් කරන්න.",
    "Probe the chilled goods as they come off the truck.": "ට්‍රක් රථයෙන් බාන විට සිසිල් භාණ්ඩවල උෂ්ණත්වය මනින්න.",
    "on arrival": "පැමිණීමේදී",
  },
  ta: {
    "Estimated order volume for the next ten weeks, by depot and brand, to plan vehicles, drivers and refrigerated capacity.": "வாகனங்கள், ஓட்டுநர்கள் மற்றும் குளிரூட்டல் திறனைத் திட்டமிட, கிடங்கு மற்றும் பிராண்ட் வாரியாக அடுத்த பத்து வாரங்களுக்கான மதிப்பிடப்பட்ட ஆர்டர் அளவு.",
    "widens with distance": "தூரம் கூடும்போது விரிவடைகிறது",
    "Operating calendar set up to": "செயல்பாட்டு நாட்காட்டி அமைக்கப்பட்டுள்ளது",
    "Later days use the usual weekday pattern.": "பிந்தைய நாட்கள் வழக்கமான வார நாள் முறையைப் பயன்படுத்துகின்றன.",
    "Operating calendar is not set for these weeks. Days use the usual weekday pattern.": "இந்த வாரங்களுக்கு செயல்பாட்டு நாட்காட்டி அமைக்கப்படவில்லை. நாட்கள் வழக்கமான வார நாள் முறையைப் பயன்படுத்துகின்றன.",
    "may be delayed by": "இதனால் தாமதமாகலாம்:",
    "may delay": "தாமதப்படுத்தலாம்",
    "issues on this trip": "இந்தப் பயணத்தில் சிக்கல்கள்",
    "Acknowledge all": "அனைத்தையும் ஏற்றுக்கொள்",
    "Ranked by impact and grouped by trip: breakdowns and chilled goods, closing windows, silent trips, road risks, then loading and delivery issues": "தாக்கத்தின்படி வரிசைப்படுத்தி பயணவாரியாகக் குழுவாக்கப்பட்டது: பழுதுகள் மற்றும் குளிரூட்டப்பட்ட பொருட்கள், மூடும் நேர இடைவெளிகள், அமைதியான பயணங்கள், சாலை அபாயங்கள், பின்னர் ஏற்றுதல் மற்றும் விநியோகச் சிக்கல்கள்",
    "Hearing": "கேட்பது",
    "Listening… say the items and quantities, then tap Stop.": "கேட்கிறது… பொருட்களையும் அளவுகளையும் சொல்லி, பின்னர் நிறுத்து என்பதைத் தட்டவும்.",
    "Speak your order": "உங்கள் ஆர்டரைச் சொல்லுங்கள்",
    "Paste, type or speak your order": "உங்கள் ஆர்டரை ஒட்டவும், தட்டச்சு செய்யவும் அல்லது சொல்லவும்",
    "Microphone access is blocked. Allow the microphone for this site, or type the order.": "மைக்ரோஃபோன் அணுகல் தடுக்கப்பட்டுள்ளது. இந்தத் தளத்திற்கு மைக்ரோஃபோனை அனுமதிக்கவும், அல்லது ஆர்டரைத் தட்டச்சு செய்யவும்.",
    "No microphone was found. Type the order instead.": "மைக்ரோஃபோன் எதுவும் கிடைக்கவில்லை. அதற்குப் பதிலாக ஆர்டரைத் தட்டச்சு செய்யவும்.",
    "Speech could not be turned into text without a connection. Type the order instead.": "இணைப்பு இல்லாமல் பேச்சை உரையாக மாற்ற முடியவில்லை. அதற்குப் பதிலாக ஆர்டரைத் தட்டச்சு செய்யவும்.",
    "This browser cannot listen in the chosen language. Switch to English or type the order.": "இந்த உலாவியால் தேர்ந்தெடுத்த மொழியில் கேட்க முடியாது. ஆங்கிலத்திற்கு மாறவும் அல்லது ஆர்டரைத் தட்டச்சு செய்யவும்.",
    "Nothing was heard. Tap Speak and try again.": "எதுவும் கேட்கவில்லை. சொல் என்பதைத் தட்டி மீண்டும் முயற்சிக்கவும்.",
    "Temperature on arrival (°C, optional)": "வருகையின் போது வெப்பநிலை (°C, விருப்பத்தேர்வு)",
    "e.g. 4.5": "எ.கா. 4.5",
    "Enter a reading between -40 and 60 °C.": "-40 முதல் 60 °C வரையிலான அளவீட்டை உள்ளிடவும்.",
    "Probe the chilled goods as they come off the truck.": "லாரியிலிருந்து இறக்கும்போது குளிரூட்டப்பட்ட பொருட்களின் வெப்பநிலையை அளவிடவும்.",
    "on arrival": "வருகையின் போது",
  },
};
