apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: waypoint
resources:
  - namespace.yaml
  - service-accounts/service-accounts.yaml
  - configmaps/config.yaml
  - services/services.yaml
  - deployments/deployments.yaml
  - network-policies/network-policies.yaml
  - gateway/gateway.yaml
  - gateway/routes/httproutes.yaml
