apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: waypoint/order-service
    newTag: dev
  - name: waypoint/planning-service
    newTag: dev
  - name: waypoint/fleet-service
    newTag: dev
  - name: waypoint/loading-service
    newTag: dev
  - name: waypoint/delivery-service
    newTag: dev
  - name: waypoint/shared-service
    newTag: dev
  - name: waypoint/integration-service
    newTag: dev
  - name: waypoint/agent-orchestrator
    newTag: dev
  - name: waypoint/web
    newTag: dev
