ALTER TABLE loading.sessions
    ADD COLUMN IF NOT EXISTS trip_number INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS vehicle_type TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS vehicle_temperature_capability TEXT NOT NULL DEFAULT '';

ALTER TABLE loading.order_loads
    ADD COLUMN IF NOT EXISTS order_ref TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS outlet_id TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS brand TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS temperature_requirement TEXT NOT NULL DEFAULT '';
